name: Publish to NPM

on:
  release:
    types: [published]  # Trigger when you manually create a GitHub release

# Prevent duplicate runs from npm version workflow
concurrency:
  group: npm-publish
  cancel-in-progress: true

permissions:
  contents: write  # Required to create releases and tags
  packages: read   # Required to read packages

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: |
          cd installer
          npm ci
          
      - name: Extract version from release tag
        id: version-check
        run: |
          cd installer
          # Extract version from GitHub release tag (e.g., v1.4.3 -> 1.4.3)
          RELEASE_VERSION="${{ github.event.release.tag_name }}"
          NEW_VERSION=${RELEASE_VERSION#v}  # Remove 'v' prefix
          
          CURRENT_VERSION=$(npm view context-engineering-installer version || echo "0.0.0")
          echo "current=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "package=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "changed=true" >> $GITHUB_OUTPUT  # Always publish on release
          echo "Publishing release $RELEASE_VERSION as npm version $NEW_VERSION"
          
          # Update package.json to match release tag
          npm version $NEW_VERSION --no-git-tag-version
          
      - name: Publish to NPM
        if: steps.version-check.outputs.changed == 'true'
        run: |
          cd installer
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Generate changelog
        if: steps.version-check.outputs.changed == 'true'
        id: changelog
        run: |
          cd installer
          # Get commit messages since last tag
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$LAST_TAG" ]; then
            COMMITS=$(git log --oneline --pretty=format:"- %s (%h)" --no-merges)
          else
            COMMITS=$(git log ${LAST_TAG}..HEAD --oneline --pretty=format:"- %s (%h)" --no-merges)
          fi
          
          # Save changelog to output
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "## Changes in v${{ steps.version-check.outputs.package }}" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          if [ -n "$COMMITS" ]; then
            echo "$COMMITS" >> $GITHUB_OUTPUT
          else
            echo "- Package updates and improvements" >> $GITHUB_OUTPUT
          fi
          echo "" >> $GITHUB_OUTPUT
          echo "**NPM Package:** [context-engineering-installer@${{ steps.version-check.outputs.package }}](https://npmjs.com/package/context-engineering-installer)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: Create GitHub Release
        if: steps.version-check.outputs.changed == 'true'
        run: |
          gh release create "v${{ steps.version-check.outputs.package }}" \
            --title "Release v${{ steps.version-check.outputs.package }}" \
            --notes "${{ steps.changelog.outputs.changelog }}" \
            --latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}